sonar.projectKey=lavenbloom-auth-service
sonar.projectName=lavenbloom-auth-service
sonar.sources=.

sonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/migrations/**,tests/**

sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml